### ISSUE TITLE
Fix [BUG]Unable to link with vault, this is my server log

### ISSUE THREAD

**Issue by xiaoyiluck666** [Sv3ks/HyperCurrencies#22]
![image](https://user-images.githubusercontent.com/83876597/235506137-38ce33ac-0c33-4154-ae06-3a13a09e485a.png)
![image](https://user-images.githubusercontent.com/83876597/235506197-cd09fd41-45a6-4395-9971-5908b0a14a75.png)
I tested the English currency name and Chinese currency name, both can not be linked with vault, I am paper 1.19.4 version java 19

**Comment by xiaoyiluck666** [comment]
[latest.log](https://github.com/Sv3ks/HyperCurrencies/files/11367222/latest.log)

**Comment by Sv3ks** [comment]
I think you're talking about the wrong plugin. As you can see in the log, it's logged by "CMI", not hc.
