### ISSUE TITLE
Baltop pages

### ISSUE THREAD

**Issue by Sv3ks** [Sv3ks/HyperCurrencies#4]
I was looking and the baltop only goes up to 10 if I'm not mistaken, it would be like the other economy plugins that as they enter users go increasing, for example if the maximum baltop today are 20 people and tomorrow I enter 10 more than you when you put /baltop 2 I get from 11 to 20 and so on with the other pages that is how it does for example the essentials and placeholders of top same

_Originally posted by @Zarkness in https://github.com/Sv3ks/HyperCurrencies/issues/1#issuecomment-1500671723_

**Comment by Zarkness2** [comment]
one thing, what are the placeholders you added?

**Comment by Sv3ks** [comment]
%hypercurrencies_balance_<player>% is the only one for now, more will come later on.
